package org.shelk.utils;

public enum XParticle {
	
	FLAME,VILLAGER_HAPPY,CLOUD,NOTE,REDSTONE,SNOW_SHOVEL,DRIP_LAVA,DRIP_WATER,LAVA,EXPLOSION_LARGE,HEART,
	FIREWORKS_SPARK,PORTAL,ENCHANTMENT_TABLE,CRIT,SPELL,SPELL_WITCH,SLIME,VILLAGER_ANGRY,SMOKE_NORMAL,
	WATER_BUBBLE;
	
	


	
}